name: CI and CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ==============
  # CI task
  # ==============
  Testing:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-20.04
    needs: Testing
    
    steps:
    - name: Setup SHA
      run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
    
#     - name: Build the Docker image
#       run: docker build ./BlazorAppDev/Server --file Dockerfile --tag blazorappdev-image:${{ env.GITHUB_SHA }}

    - name: Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: copterbuddy/blazorappdev:latest
